const ADD_TASK = "ADD_TASK";
const DELETE_TASK = "DELETE_TASK";
const EDIT_TASK = "EDIT_TASK";
const TOGGLE_TASK_COMPLETED = "TOGGLE_TASK_COMPLETED";
const ADD_SUBTASK = "ADD_SUBTASK";
const DELETE_SUBTASK = "DELETE_SUBTASK";
const TOGGLE_SUBTASK_COMPLETED = "TOGGLE_SUBTASK_COMPLETED";

export { 
    ADD_TASK,
    DELETE_TASK, 
    EDIT_TASK, 
    TOGGLE_TASK_COMPLETED, 
    ADD_SUBTASK, 
    DELETE_SUBTASK, 
    TOGGLE_SUBTASK_COMPLETED 
}